.\" $Id$
.Dd January 24, 2004
.Dt QPOPAUTHD 8
.Os
.Sh NAME
.Nm qpopauthd 
.Nd "Qpopper/POP3 authentication daemon"
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl a Ar accessfile
.Op Fl d Ar timeout
.Sh DESCRIPTION
.Nm
reads lines from standard input continually looking for a
pattern denoting successful authorization. Once found, 
.Nm
extracts the information from the input and creates
a new authentication record in the mail access list.
.Pp
Whenever a subsequent, matching log message is read, the
authentication record is updated. After the last message
has been read and the predetermined timeout period has been
reached for a particular authentication record, the record
is removed.
.Sh OPTIONS
.Bl -tag -width xx
.It Fl a Ar accessfile
Specify the mail access list file. The default is
.Pa /etc/mail/access .
.It Fl d Ar timeout
Specify the timeout period. The default is five minutes.
.It Fl h
Print out short usage information.
.El
.Sh FILES
.Bl -tag -width "/etc/mail/access" -compact
.Pa /etc/mail/access
The default mail access list file.
.El
.Sh NOTES
It's silly to feed authorization messages to
.Nm
manually.  The usual invocation is something like this:
.Bd -literal -offset indent
$ tail -f /var/log/mailaccess | qpopauthd &
.Ed
.Sh AUTHOR
Jared Yanovich <jaredy@closeedge.net>
